[package]
name = "frei0r-sys"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/kenkinming2002/frei0r-rs"
description = "Sys crate for frei0r-rs"

[build-dependencies]
bindgen = "0.69.4"
